all:
  vars:
    control_plane_endpoint: 192.168.5.20
    load_balancer_ip_pool:
      - 192.168.5.30/28
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.5.20, mac: 'c8:5b:76:cd:18:25', disk: sda, network_interface: eno1}
    workers:
      hosts:
